const words = [
   
];

const kanjiWords = [
    { "id": 751, "kanji": "駐車", "hiragana": "ちゅうしゃ", "meaning": "Đỗ xe" },
    { "id": 752, "kanji": "駐車場", "hiragana": "ちゅうしゃじょう", "meaning": "Bãi đỗ xe" },
    { "id": 753, "kanji": "無休", "hiragana": "むきゅう", "meaning": "Không nghỉ" },
    { "id": 754, "kanji": "無料", "hiragana": "むりょう", "meaning": "Miễn phí" },
    { "id": 755, "kanji": "無理", "hiragana": "むり", "meaning": "Cố sức, không hợp lý" },
    { "id": 756, "kanji": "無い", "hiragana": "ない", "meaning": "Không có, không tồn tại" },
    { "id": 757, "kanji": "満車", "hiragana": "まんしゃ", "meaning": "Đầy xe" },
    { "id": 758, "kanji": "満員", "hiragana": "まんいん", "meaning": "Đầy người" },
    { "id": 759, "kanji": "不満", "hiragana": "ふまん", "meaning": "Bất mãn" },
    { "id": 760, "kanji": "方向", "hiragana": "ほうこう", "meaning": "Phương hướng" },
    { "id": 761, "kanji": "向こう", "hiragana": "むこう", "meaning": "Phía bên kia" },
    { "id": 762, "kanji": "向かう", "hiragana": "むかう", "meaning": "Hướng về" },
    { "id": 763, "kanji": "禁止", "hiragana": "きんし", "meaning": "Cấm đoán" },
    { "id": 764, "kanji": "関心", "hiragana": "かんしん", "meaning": "Quan tâm" },
    { "id": 765, "kanji": "関する", "hiragana": "かんする", "meaning": "Liên quan đến" },
    { "id": 766, "kanji": "関係", "hiragana": "かんけい", "meaning": "Mối quan hệ" },
    { "id": 767, "kanji": "係", "hiragana": "かかり", "meaning": "Người phụ trách" },
    { "id": 768, "kanji": "無断", "hiragana": "むだん", "meaning": "Không được phép" },
    { "id": 769, "kanji": "断水", "hiragana": "だんすい", "meaning": "Cắt nước" },
    { "id": 770, "kanji": "断る", "hiragana": "ことわる", "meaning": "Từ chối" },
    { "id": 771, "kanji": "横断", "hiragana": "おうだん", "meaning": "Băng ngang qua (đường)" },
    { "id": 772, "kanji": "横断歩道", "hiragana": "おうだんほどう", "meaning": "Lối băng qua đường" },
    { "id": 773, "kanji": "横", "hiragana": "よこ", "meaning": "Ngang, bên cạnh, bên hông" },
    { "id": 774, "kanji": "押す", "hiragana": "おす", "meaning": "Ấn, nhấn" },
    { "id": 775, "kanji": "押し入れ", "hiragana": "おしいれ", "meaning": "Tủ chìm (âm tường)" },
    { "id": 776, "kanji": "押さえる", "hiragana": "おさえる", "meaning": "Nhấn giữ (nút), giữ lại" },
    { "id": 777, "kanji": "式", "hiragana": "しき", "meaning": "Nghi thức, kiểu cách" },
    { "id": 778, "kanji": "入学式", "hiragana": "にゅうがくしき", "meaning": "Lễ khai giảng, lễ nhập trường" },
    { "id": 779, "kanji": "数式", "hiragana": "すうしき", "meaning": "Công thức số" },
    { "id": 780, "kanji": "送信", "hiragana": "そうしん", "meaning": "Gửi (email...)" },
    { "id": 781, "kanji": "自信", "hiragana": "じしん", "meaning": "Tự tin" },
    { "id": 782, "kanji": "信じる", "hiragana": "しんじる", "meaning": "Tin vào (tin tưởng)" },
    { "id": 783, "kanji": "信用", "hiragana": "しんよう", "meaning": "Tin tưởng, tín nhiệm" },
    { "id": 784, "kanji": "信号", "hiragana": "しんごう", "meaning": "Đèn tín hiệu" },
    { "id": 785, "kanji": "号車", "hiragana": "ごうしゃ", "meaning": "Toa (tàu) số..." },
    { "id": 786, "kanji": "正確", "hiragana": "せいかく", "meaning": "Chính xác" },
    { "id": 787, "kanji": "確か", "hiragana": "たしか", "meaning": "Chính xác, chắc chắn" },
    { "id": 788, "kanji": "確かめる", "hiragana": "たしかめる", "meaning": "Xác nhận, kiểm tra" },
    { "id": 789, "kanji": "確認", "hiragana": "かくにん", "meaning": "Sự xác nhận" },
    { "id": 790, "kanji": "認める", "hiragana": "みとめる", "meaning": "Chấp nhận, cho phép" },
    { "id": 791, "kanji": "飛行場", "hiragana": "ひこうじょう", "meaning": "Sân bay" },
    { "id": 792, "kanji": "飛ぶ", "hiragana": "とぶ", "meaning": "Bay" }
];