const words = [
    { "id": 700, "kanji": "商売", "hiragana": "しょうばい", "meaning": "Kinh doanh, buôn bán" },
    { "id": 701, "kanji": "商品", "hiragana": "しょうひん", "meaning": "Sản phẩm, hàng hóa" },
    { "id": 702, "kanji": "質", "hiragana": "しつ", "meaning": "Chất lượng, bản chất" },
    { "id": 703, "kanji": "型", "hiragana": "かた", "meaning": "Kiểu mẫu, mô hình" },
    { "id": 704, "kanji": "生産", "hiragana": "せいさん", "meaning": "Sản xuất" },
    { "id": 705, "kanji": "消費", "hiragana": "しょうひ", "meaning": "Tiêu dùng, tiêu thụ" },
    { "id": 706, "kanji": "物価", "hiragana": "ぶっか", "meaning": "Vật giá" },
    { "id": 707, "kanji": "倒産", "hiragana": "とうさん", "meaning": "Phá sản" },
    { "id": 708, "kanji": "携帯", "hiragana": "けいたい", "meaning": "Mang theo, di động" },
    { "id": 709, "kanji": "現代", "hiragana": "げんだい", "meaning": "Hiện đại, thời nay" },
    { "id": 710, "kanji": "世紀", "hiragana": "せいき", "meaning": "Thế kỷ" },
    { "id": 711, "kanji": "文化", "hiragana": "ぶんか", "meaning": "Văn hóa" },
    { "id": 712, "kanji": "都市", "hiragana": "とし", "meaning": "Thành phố, đô thị" },
    { "id": 713, "kanji": "地方", "hiragana": "ちほう", "meaning": "Địa phương, vùng miền" },
    { "id": 714, "kanji": "戦争", "hiragana": "せんそう", "meaning": "Chiến tranh" },
    { "id": 715, "kanji": "平和", "hiragana": "へいわ", "meaning": "Hòa bình" },
    { "id": 716, "kanji": "上る", "hiragana": "のぼる", "meaning": "Leo lên, tăng lên" },
    { "id": 717, "kanji": "下る", "hiragana": "くだる", "meaning": "Đi xuống, giảm xuống" },
    { "id": 718, "kanji": "進む", "hiragana": "すすむ", "meaning": "Tiến lên, tiến triển" },
    { "id": 719, "kanji": "進める", "hiragana": "すすめる", "meaning": "Thúc đẩy, tiến hành" },
    { "id": 720, "kanji": "通る", "hiragana": "とおる", "meaning": "Đi qua, thông qua" },
    { "id": 721, "kanji": "通す", "hiragana": "とおす", "meaning": "Cho đi qua, xuyên qua" },
    { "id": 722, "kanji": "超える / 越える", "hiragana": "こえる", "meaning": "Vượt qua" },
    { "id": 723, "kanji": "過ぎる", "hiragana": "すぎる", "meaning": "Quá, vượt quá" },
    { "id": 724, "kanji": "過ごす", "hiragana": "すごす", "meaning": "Trải qua, dành thời gian" },
    { "id": 725, "kanji": "移る", "hiragana": "うつる", "meaning": "Di chuyển, lây lan" },
    { "id": 726, "kanji": "移す", "hiragana": "うつす", "meaning": "Di dời, chuyển đi" },
    { "id": 727, "kanji": "連れる", "hiragana": "つれる", "meaning": "Dẫn theo, đưa đi cùng" },
    { "id": 728, "kanji": "寄る", "hiragana": "よる", "meaning": "Ghé vào, lại gần" },
    { "id": 729, "kanji": "寄せる", "hiragana": "よせる", "meaning": "Dời sang, tập trung vào" },
    { "id": 730, "kanji": "与える", "hiragana": "あたえる", "meaning": "Ban cho, cung cấp" },
    { "id": 731, "kanji": "得る", "hiragana": "える", "meaning": "Nhận được, có được" },
    { "id": 732, "kanji": "向く", "hiragana": "むく", "meaning": "Hướng về, phù hợp với" },
    { "id": 733, "kanji": "向ける", "hiragana": "むける", "meaning": "Hướng đến, dành cho" },
    { "id": 734, "kanji": "勧める", "hiragana": "すすめる", "meaning": "Khuyên, khuyến khích" },
    { "id": 735, "kanji": "薦める", "hiragana": "すすめる", "meaning": "Giới thiệu, đề xuất" },
    { "id": 736, "kanji": "任せる", "hiragana": "まかせる", "meaning": "Giao phó, để cho làm" },
    { "id": 737, "kanji": "守る", "hiragana": "まもる", "meaning": "Bảo vệ, tuân thủ" },
    { "id": 738, "kanji": "争う", "hiragana": "あらそう", "meaning": "Tranh giành, đấu tranh" },
    { "id": 739, "kanji": "望む", "hiragana": "のぞむ", "meaning": "Mong muốn, hy vọng" },
    { "id": 740, "kanji": "信じる", "hiragana": "しんじる", "meaning": "Tin tưởng, tin vào" },
    { "id": 741, "kanji": "通じる", "hiragana": "つうじる", "meaning": "Thông hiểu, dẫn đến" },
    { "id": 742, "kanji": "飽きる", "hiragana": "あきる", "meaning": "Chán, ngán" },
    { "id": 743, "kanji": "思いつく", "hiragana": "おもいつく", "meaning": "Nghĩ ra, nảy ra ý tưởng" },
    { "id": 744, "kanji": "思いやる", "hiragana": "おもいやる", "meaning": "Quan tâm, thông cảm" },
    { "id": 745, "kanji": "熱中する", "hiragana": "ねっちゅうする", "meaning": "Mải mê, đam mê" },
    { "id": 746, "kanji": "暮らす", "hiragana": "くらす", "meaning": "Sống, sinh hoạt" },
    { "id": 747, "kanji": "巻く", "hiragana": "まく", "meaning": "Cuộn lại, quấn lại" },
    { "id": 748, "kanji": "結ぶ", "hiragana": "むすぶ", "meaning": "Buộc, kết nối" },
    { "id": 749, "kanji": "済む", "hiragana": "すむ", "meaning": "Hoàn thành, kết thúc" },
    { "id": 750, "kanji": "済ませる / 済ます", "hiragana": "すませる / すます", "meaning": "Làm xong, hoàn tất" }
];

const kanjiWords = [
    { "id": 751, "kanji": "駐車", "hiragana": "ちゅうしゃ", "meaning": "Đỗ xe" },
    { "id": 752, "kanji": "駐車場", "hiragana": "ちゅうしゃじょう", "meaning": "Bãi đỗ xe" },
    { "id": 753, "kanji": "無休", "hiragana": "むきゅう", "meaning": "Không nghỉ" },
    { "id": 754, "kanji": "無料", "hiragana": "むりょう", "meaning": "Miễn phí" },
    { "id": 755, "kanji": "無理", "hiragana": "むり", "meaning": "Cố sức, không hợp lý" },
    { "id": 756, "kanji": "無い", "hiragana": "ない", "meaning": "Không có, không tồn tại" },
    { "id": 757, "kanji": "満車", "hiragana": "まんしゃ", "meaning": "Đầy xe" },
    { "id": 758, "kanji": "満員", "hiragana": "まんいん", "meaning": "Đầy người" },
    { "id": 759, "kanji": "不満", "hiragana": "ふまん", "meaning": "Bất mãn, không hài lòng" },
    { "id": 760, "kanji": "方向", "hiragana": "ほうこう", "meaning": "Phương hướng" },
    { "id": 761, "kanji": "向かう", "hiragana": "むかう", "meaning": "Hướng về (phía)" },
    { "id": 762, "kanji": "向こう", "hiragana": "むこう", "meaning": "Bên kia, đằng kia" },
    { "id": 763, "kanji": "○○向き", "hiragana": "むき", "meaning": "Thích hợp với ○○" },
    { "id": 764, "kanji": "禁止", "hiragana": "きんし", "meaning": "Cấm đoán" },
    { "id": 765, "kanji": "関心", "hiragana": "かんしん", "meaning": "Quan tâm" },
    { "id": 766, "kanji": "関する", "hiragana": "かんする", "meaning": "Liên quan tới" },
    { "id": 767, "kanji": "関係", "hiragana": "かんけい", "meaning": "Quan hệ, liên quan" },
    { "id": 768, "kanji": "係", "hiragana": "かかり", "meaning": "Người phụ trách" },
    { "id": 769, "kanji": "無断", "hiragana": "むだん", "meaning": "Không được phép" },
    { "id": 770, "kanji": "断る", "hiragana": "ことわる", "meaning": "Từ chối" },
    { "id": 771, "kanji": "断水", "hiragana": "だんすい", "meaning": "Cắt nước" },
    { "id": 772, "kanji": "横断", "hiragana": "おうだん", "meaning": "Băng ngang qua (đường)" },
    { "id": 773, "kanji": "横", "hiragana": "よこ", "meaning": "Ngang, bên cạnh, bề ngang" },
    { "id": 774, "kanji": "横断歩道", "hiragana": "おうだんほどう", "meaning": "Lối băng qua đường" },
    { "id": 775, "kanji": "押す", "hiragana": "おす", "meaning": "Ấn, nhấn" },
    { "id": 776, "kanji": "押さえる", "hiragana": "おさえる", "meaning": "Nhấn giữ (nút), giữ lại" },
    { "id": 777, "kanji": "押し入れ", "hiragana": "おしいれ", "meaning": "Tủ chìm (âm tường)" },
    { "id": 778, "kanji": "押しボタン式", "hiragana": "おしぼたんしき", "meaning": "Kiểu có nút nhấn" },
    { "id": 779, "kanji": "入学式", "hiragana": "にゅうがくしき", "meaning": "Lễ khai giảng, lễ nhập trường" },
    { "id": 780, "kanji": "数式", "hiragana": "すうしき", "meaning": "Công thức số" },
    { "id": 781, "kanji": "送信", "hiragana": "そうしん", "meaning": "Gửi (email...)" },
    { "id": 782, "kanji": "自信", "hiragana": "じしん", "meaning": "Tự tin" },
    { "id": 783, "kanji": "信じる", "hiragana": "しんじる", "meaning": "Tin vào (tin)" },
    { "id": 784, "kanji": "信用", "hiragana": "しんよう", "meaning": "Tin tưởng, tín nhiệm" },
    { "id": 785, "kanji": "信号", "hiragana": "しんごう", "meaning": "Đèn tín hiệu" },
    { "id": 786, "kanji": "〜号車", "hiragana": "ごうしゃ", "meaning": "Toa (tàu) số..." },
    { "id": 787, "kanji": "正確", "hiragana": "せいかく", "meaning": "Chính xác" },
    { "id": 788, "kanji": "確か", "hiragana": "たしか", "meaning": "Chắc chắn, chính xác" },
    { "id": 789, "kanji": "確かめる", "hiragana": "たしかめる", "meaning": "Xác nhận" },
    { "id": 790, "kanji": "確認", "hiragana": "かくにん", "meaning": "Sự xác nhận" },
    { "id": 791, "kanji": "認める", "hiragana": "みとめる", "meaning": "Chấp nhận, cho phép" },
    { "id": 792, "kanji": "飛行場", "hiragana": "ひこうじょう", "meaning": "Sân bay" },
    { "id": 793, "kanji": "飛ぶ", "hiragana": "とぶ", "meaning": "Bay" },
    { "id": 794, "kanji": "非常", "hiragana": "ひじょう", "meaning": "Khẩn cấp, cấp bách" },
    { "id": 795, "kanji": "非常口", "hiragana": "ひじょうぐち", "meaning": "Cửa thoát hiểm" },
    { "id": 796, "kanji": "日常", "hiragana": "にちじょう", "meaning": "Thường ngày, hàng ngày" },
    { "id": 797, "kanji": "正常", "hiragana": "せいじょう", "meaning": "Bình thường" },
    { "id": 798, "kanji": "〜階", "hiragana": "かい", "meaning": "Tầng (lầu)" },
    { "id": 799, "kanji": "階段", "hiragana": "かいだん", "meaning": "Cầu thang" },
    { "id": 800, "kanji": "箱", "hiragana": "はこ", "meaning": "Cái hộp" },
    { "id": 801, "kanji": "ごみ箱", "hiragana": "ごみばこ", "meaning": "Thùng rác" },
    { "id": 802, "kanji": "危険", "hiragana": "きけん", "meaning": "Nguy hiểm" },
    { "id": 803, "kanji": "危ない", "hiragana": "あぶない", "meaning": "Nguy hiểm, nguy cấp" },
    { "id": 804, "kanji": "捨てる", "hiragana": "すてる", "meaning": "Vứt bỏ, ném đi" }
]